### ISSUE TITLE
Security

### ISSUE THREAD

**Issue by DeveloperTK** [CookingAtKIT/cak-core#22]
no

**Comment by yJulian** [comment]
When you hash the password at the frontend you give a potential hacker access to the used alogorythems and methods. Also a client could manipulate a hash at the client. When you hash it at the serverside an attacker cant get access to that information.
Also the transpotationlayer (SSL / HTTPS) is what i consider safe enough

**Comment by finnmglas** [comment]
I suppose we close the issue then :+1:
